# Generated by Django 4.0.3 on 2022-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_familiares', '0002_familiares_id_alter_familiares_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
