# Generated by Django 4.0.3 on 2022-04-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_familiares', '0003_alter_familiares_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='id',
            new_name='pkid',
        ),
    ]
