# Generated by Django 4.0.3 on 2022-04-05 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_familiares', '0006_familiares_pkid_alter_familiares_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='pkid',
        ),
        migrations.AlterField(
            model_name='familiares',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 4, 5, 22, 55, 14, 930142, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
